# Generated by Django 5.0.1 on 2024-01-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersite',
            name='site_url',
        ),
    ]
